# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: false
latex: false
fortran: false

matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3

addons:
  apt:
    packages:
    - libssl-dev
    - git
    - openssh-client
