# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
latex: false
fortran: false

matrix:
  include:
    - r: 3.3
      dist: trusty
      warnings_are_errors: false
    - os: linux
      warnings_are_errors: false
    - os: osx
      osx_image: xcode11.4
    - os: osx
      osx_image: xcode10.1

addons:
  apt:
    packages:
    - libssl-dev
    - git
    - ssh-client
